const wordMatrix = [
  {
    id: 0,
    word: 'Self Controlled',
    wordnum: 1,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 1,
    word: 'Conscientious',
    wordnum: 2,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 2,
    word: 'Striving',
    wordnum: 3,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 3,
    word: 'Orderly',
    wordnum: 4,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 4,
    word: 'Perfectionistic',
    wordnum: 5,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L6',
    center: 'IN',
  },
  {
    id: 5,
    word: 'Obligated',
    wordnum: 6,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 6,
    word: 'Punctual',
    wordnum: 7,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 7,
    word: 'Serious',
    wordnum: 8,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 8,
    word: 'Correcting',
    wordnum: 9,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L6',
    center: 'IN',
  },
  {
    id: 9,
    word: 'Critical',
    wordnum: 10,
    primary: 'R',
    secondary: 'o',
    type: 1,
    level: 'L6',
    center: 'IN',
  },
  {
    id: 10,
    word: 'Needing closeness',
    wordnum: 11,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 11,
    word: 'Nurturing',
    wordnum: 12,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 12,
    word: 'Generous to a Fault',
    wordnum: 13,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 13,
    word: 'Serving',
    wordnum: 14,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 14,
    word: 'Deeply Caring',
    wordnum: 15,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L2',
    center: 'FE',
  },
  {
    id: 15,
    word: 'Generous',
    wordnum: 16,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 16,
    word: 'People person',
    wordnum: 17,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 17,
    word: 'Martyring Self',
    wordnum: 18,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L6',
    center: 'FE',
  },
  {
    id: 18,
    word: 'Possessive',
    wordnum: 19,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 19,
    word: 'Approving',
    wordnum: 20,
    primary: 'G',
    secondary: 'f',
    type: 2,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 20,
    word: 'Charming',
    wordnum: 21,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L2',
    center: 'FE',
  },
  {
    id: 21,
    word: 'Performing',
    wordnum: 22,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 22,
    word: 'Role model',
    wordnum: 23,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 23,
    word: 'Appropriate',
    wordnum: 24,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 24,
    word: 'Ambitious',
    wordnum: 25,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 25,
    word: 'Efficient',
    wordnum: 26,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 26,
    word: 'The Best',
    wordnum: 27,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 27,
    word: 'Arrogant',
    wordnum: 28,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L6',
    center: 'FE',
  },
  {
    id: 28,
    word: 'Seek Recognition',
    wordnum: 29,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 29,
    word: 'Image Conscious',
    wordnum: 30,
    primary: 'G',
    secondary: 'g',
    type: 3,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 30,
    word: 'Self Indulgent',
    wordnum: 31,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L6',
    center: 'FE',
  },
  {
    id: 31,
    word: 'Self-Absorbed',
    wordnum: 32,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 32,
    word: 'Introspective',
    wordnum: 33,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L2',
    center: 'FE',
  },
  {
    id: 33,
    word: 'Mysterious',
    wordnum: 34,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 34,
    word: 'Special',
    wordnum: 35,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 35,
    word: 'Self-Revealing',
    wordnum: 36,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L3',
    center: 'FE',
  },
  {
    id: 36,
    word: 'Brooding',
    wordnum: 37,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 37,
    word: 'Self-Pitying',
    wordnum: 38,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L6',
    center: 'FE',
  },
  {
    id: 38,
    word: 'Aesthetic',
    wordnum: 39,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L4',
    center: 'FE',
  },
  {
    id: 39,
    word: 'Temperamental',
    wordnum: 40,
    primary: 'G',
    secondary: 't',
    type: 4,
    level: 'L5',
    center: 'FE',
  },
  {
    id: 40,
    word: 'Unsentimental',
    wordnum: 41,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 41,
    word: 'Inventive',
    wordnum: 42,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 42,
    word: 'Intense',
    wordnum: 43,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 43,
    word: 'Speculative',
    wordnum: 44,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 44,
    word: 'Detached',
    wordnum: 45,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 45,
    word: 'Specialized',
    wordnum: 46,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 46,
    word: 'Subversive',
    wordnum: 47,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L6',
    center: 'TH',
  },
  {
    id: 47,
    word: 'Analytical',
    wordnum: 48,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 48,
    word: 'Secretive',
    wordnum: 49,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 49,
    word: 'Curious',
    wordnum: 50,
    primary: 'B',
    secondary: 'l',
    type: 5,
    level: 'L2',
    center: 'TH',
  },
  {
    id: 50,
    word: 'Doubting',
    wordnum: 51,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 51,
    word: 'Worrying',
    wordnum: 52,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 52,
    word: 'Suspicious',
    wordnum: 53,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L6',
    center: 'TH',
  },
  {
    id: 53,
    word: 'Vigilant',
    wordnum: 54,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L2',
    center: 'TH',
  },
  {
    id: 54,
    word: 'Cautious',
    wordnum: 55,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 55,
    word: 'Prepared',
    wordnum: 56,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 56,
    word: 'Cooperative',
    wordnum: 57,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 57,
    word: 'Ambivalent',
    wordnum: 58,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 58,
    word: 'Dutiful',
    wordnum: 59,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 59,
    word: 'Committed',
    wordnum: 60,
    primary: 'B',
    secondary: 'b',
    type: 6,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 60,
    word: 'Keep options open',
    wordnum: 61,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 61,
    word: 'Accomplished',
    wordnum: 62,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 62,
    word: 'Versatile',
    wordnum: 63,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L3',
    center: 'TH',
  },
  {
    id: 63,
    word: 'Spontaneous',
    wordnum: 64,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L2',
    center: 'TH',
  },
  {
    id: 64,
    word: 'Uninhibited',
    wordnum: 65,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 65,
    word: 'Seeking Variety',
    wordnum: 66,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L4',
    center: 'TH',
  },
  {
    id: 66,
    word: 'Irreverent',
    wordnum: 67,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 67,
    word: 'Hyperactive',
    wordnum: 68,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 68,
    word: 'Excessive',
    wordnum: 69,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L6',
    center: 'TH',
  },
  {
    id: 69,
    word: 'Scattered',
    wordnum: 70,
    primary: 'B',
    secondary: 'w',
    type: 7,
    level: 'L5',
    center: 'TH',
  },
  {
    id: 70,
    word: 'Empowering',
    wordnum: 71,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 71,
    word: 'Protective',
    wordnum: 72,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 72,
    word: 'No Nonsense',
    wordnum: 73,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 73,
    word: 'Decisive',
    wordnum: 74,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 74,
    word: 'Territorial',
    wordnum: 75,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 75,
    word: 'Risk Taking',
    wordnum: 76,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 76,
    word: 'Dominant',
    wordnum: 77,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 77,
    word: 'Pushing Limits',
    wordnum: 78,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L6',
    center: 'IN',
  },
  {
    id: 78,
    word: 'Assertive',
    wordnum: 79,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L2',
    center: 'IN',
  },
  {
    id: 79,
    word: 'Tough',
    wordnum: 80,
    primary: 'R',
    secondary: 'p',
    type: 8,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 80,
    word: 'Stubborn',
    wordnum: 81,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L6',
    center: 'IN',
  },
  {
    id: 81,
    word: 'Easygoing',
    wordnum: 82,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 82,
    word: 'Mediating',
    wordnum: 83,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 83,
    word: 'Agreeable',
    wordnum: 84,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 84,
    word: 'Patient',
    wordnum: 85,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L3',
    center: 'IN',
  },
  {
    id: 85,
    word: 'Comfort Seeking',
    wordnum: 86,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 86,
    word: 'Self Effacing',
    wordnum: 87,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L4',
    center: 'IN',
  },
  {
    id: 87,
    word: 'Unselfconscious',
    wordnum: 88,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L2',
    center: 'IN',
  },
  {
    id: 88,
    word: 'Avoid Conflicts',
    wordnum: 89,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L5',
    center: 'IN',
  },
  {
    id: 89,
    word: 'Neutral',
    wordnum: 90,
    primary: 'R',
    secondary: 'r',
    type: 9,
    level: 'L5',
    center: 'IN',
  },
];
